### ISSUE TITLE
Gtfcuff auc gives AUC higher than 1

### ISSUE THREAD

**Issue by LehmannN** [Kingsford-Group/rnaseqtools#3]
Hello, 

Is there an explanation why `gtfcuff auc` gives results higher than 1 ? 

This is an example of an output that I got: 
`reference = 197649 prediction = 24598 correct = 10626 sensitivity = 5.38 precision = 43.20 auc = 379.896`

I tried with different files and I had AUC = 300, AUC = 5000, etc. but nothing between 0 and 1 as I would expect.

Thanks in advance for your help

**Comment by shaomingfu** [comment]
Hi, the AUC value given is multiplied by a factor of 10^4. In the example you show the actual AUC will be 0.0379. (BTW, you might find this value is very small; one of the reasons is the use of the current annotation transcriptome as ground-truth, which is arguably over-annotated and incomplete. But this measure is reasonably OK to compare the *relative* performance among different methods.)

**Comment by LehmannN** [comment]
Wouldn't it make more sense to leave it without multiplying by this factor ? But thanks for the explanation !

**Comment by shaomingfu** [comment]
It definitely makes more sense without multiplying this factor. It is a programming artifact that leads to it (both sensitivity / precision are multiplied by 100 in the program), not because the number is too small. This will be fixed in the next release. BTW, the area is the one under the sensitivity-precision-curve, not the one under sensitivity-specificity-curve.

**Comment by LehmannN** [comment]
> BTW, the area is the one under the sensitivity-precision-curve

Ok, it also makes more sense. Thanks !

**Comment by shaomingfu** [comment]
Thanks for using our tool!
